FROM quay.io/keycloak/keycloak:26.0.2

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=SuperSecurePassword@123
ENV KC_DB=postgres
ENV KC_PROXY=edge
ENV KC_HOSTNAME_STRICT=false
ENV KC_HTTP_ENABLED=true

COPY docker-entrypoint.sh /opt/keycloak/docker-entrypoint.sh
RUN chmod +x /opt/keycloak/docker-entrypoint.sh

EXPOSE 8080
ENTRYPOINT ["/opt/keycloak/docker-entrypoint.sh"]
